image: gcc:6.3

before_script:
  - apt-get -q -m update || true
  - apt-get install -qq gperf
  - apt-get install -qq flex
  - apt-get install -qq bison
  - apt-get install -qq texinfo
  - apt-get install -qq texlive
  - autoreconf -vfi

build:
  script:
    - ./configure --enable-tzmap-fetch --enable-contrib || { cat config.log; false; }
    - make
    - make check || { cat test/test-suite.log; false; }
    - make V=1 distcheck
    - mkdir -p public
    - cp dateutils-*.tar.* public/
  artifacts:
    paths:
      - public
  only:
    - master

pages:
  artifacts:
    paths:
      - public
