language: c

compiler:
  - gcc

before_script:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq gperf
  - autoreconf -vfi

script: ./configure && make && make check

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
